---
# tasks file for zabbix_agent
- name: Update-ca-trust
  ansible.builtin.command: update-ca-trust
  register: ca
  changed_when: ca.rc == 0

- name: Install repository
  ansible.builtin.yum:
    name: "{{ zabbix_repo_url }}"
    state: present

- name: Install zabbix-agent
  ansible.builtin.yum:
    name: zabbix-agent
    state: present
    validate_certs: false

- name: configure zabbix-agent
  ansible.builtin.lineinfile:
    dest: "/etc/zabbix/zabbix_agentd.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^ServerActive=", line: "ServerActive={{ zabbix_server }}" }
    - { regexp: "^Server=", line: "Server={{ zabbix_server }}" }
  notify: "Restart zabbix-agent"
