---
# tasks file for zabbix_agent
- name: Install ca cert
  ansible.builtin.copy:
    src: files/ca.crt
    dest: /usr/local/share/ca-certificates/ca.crt

- name: update-ca-crt
  ansible.builtin.command: update-ca-certificates

- name: Install a .deb package repo
  ansible.builtin.apt:
    deb: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb

- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: yes

- name: Install zabbix-agent
  ansible.builtin.apt:
    name: zabbix-agent
    state: present

- name: configure zabbix-agent
  ansible.builtin.lineinfile:
    dest: "/etc/zabbix/zabbix_agentd.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^ServerActive=", line: "ServerActive={{ zabbix_server }}" }
    - { regexp: "^Server=", line: "Server={{ zabbix_server }}" }
  notify: "Restart zabbix-agent"
