---
- name: Converge
  hosts: all
  set_fact:
    ansible_facts:
      pkg_mgr: yum
  vars_files:
    - vars/main.yml
  tasks:
    - name: "Include ansible_role_zabbix_agent"
      include_role:
        name: "zabbix-agent"

