---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: centos:7
    privileged: true
    cmd:["/usr/sbin/init"]
    volumes:
      - /etc/pki/ca-trust/source/anchors:/etc/pki/ca-trust/source/anchors    
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  env:
    ANSIBLE_LOCAL_TEMP: "${WORKSPACE:-$HOME}/.ansible/tmp"
    ANSIBLE_REMOTE_TMP: /tmp
verifier:
  name: ansible
scenario:
  name: default
  idempotent: false
  test_sequence:
    - destroy
    - create
    - converge
    - verify
