---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:7
#    pre_build_image: false
provisioner:
  name: ansible
verifier:
  name: testinfra
