---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Example assertion
      ansible.builtin.assert:
        that: true

    - name: Check if pid file exists
      ansible.builtin.file: 
        path: /run/zabbix/zabbix_agentd.pid
        owner: zabbix
        group: zabbix
        mode: 0644
      
