---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Example assertion
      ansible.builtin.assert:
        that: true

    - name: Restart zabbix-agent
      ansible.builtin.service:
        name: zabbix-agent
        state: started
